default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "bookhub") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "bookhub") %>

development:
  <<: *default
  database: bookhub_development

test:
  <<: *default
  database: bookhub_test

production:
  <<: *default
  database: bookhub_production
